### PR TITLE
Maintenance: Replace Parcel with kirbyup & more

### PR DESCRIPTION
**Pull request by johannschopplich**
Hi there, first of all: What a great plugin you have built! Amongst the Panel plugins the one I use mostly.

Without changing the functionality of your plugin, I have update some parts related to its architecture. Each update is split into its own commit.

For example, Parcel is replaced with (obviously 😉) [kirbyup](https://github.com/johannschopplich/kirbyup). Also, some Prettier rules where dropped, since they solely redefined default values.

I hope those changes appeal to you!

### CODE REVIEW

**Comment by nilshoerrmann** [comment]
Thanks Johann, I'll check out your changes next week!

**Comment by johannschopplich** [comment]
Glad to hear. No rush!

**Comment by johannschopplich** [comment]
Additionally, I have:
- set up ESLint (used mainly for Vue components) and fixed the problems logged
- fixed an undefined variable reference inside the `index.php`
- removed a function leaking into PHP's global scope

**Comment by nilshoerrmann** [comment]
Thanks for all your updates to this plugin :+1: 
I plan to review your changes later this week.

**Comment by johannschopplich** [comment]
My refactors and fixes escalated quickly. 🙈 I just enjoyed learning from your codebase and tweaking a few things (hopefully positive for you) in the process. The pleasure was mostly mine. No rush. 🙂

**Comment by nilshoerrmann** [comment]
Actually, it's quite interesting to see what you changed and how 😀
Building this plugin was quite a ride because I neither work a lot with Vue nor with PHP (besides what's needed for Kirby).

**Comment by nilshoerrmann** [comment]
If you have any ideas on how to improve or extend the UI, feel free to post requests in the issues.

**Comment by johannschopplich** [comment]
Wow, for your first plugin, it's quite well written!

Of course. This (rather extensive) refactor doesn't change any core functionality.

**Comment by nilshoerrmann** [comment]
> Wow, for your first plugin, it's quite well written!

It's not the first plugin, but the most complex one. And thanks :)

**Review by nilshoerrmann — COMMENTED** [review]
I'm currently trying out your changes and with Kirby 3.5.3, I'm getting the following error in the panel:

> can't access lexical declaration 'n' before initialization

Any idea where this is coming from?

**Comment by johannschopplich** [comment]
My bad. Slipped through while refactoring. Fixed! 

(On a side note, with kirbyup in dev mode, the final source won't be minified, thus I was able to track down the issue quickly.)

**Pull request merged**
